### ISSUE TITLE
Not able to instlal in window 7 machine | 

### ISSUE THREAD

**Issue by jaiswalvineet** [jfkirk/tensorrec#118]
I have Annaconda3 installed, Python 3.6 but not able to install tensorrec module, I tried multiple times, here the error 

!pip install tensorrec
-----------------------------------------------------------------------------------------------------------

Collecting tensorrec
Collecting scipy==0.19.1 (from tensorrec)
  Using cached https://files.pythonhosted.org/packages/52/67/d9ef9b5058d4a9e3f0ae641ec151790622cbeb37f157de5773358e2bf3da/scipy-0.19.1.tar.gz
Requirement already satisfied: six==1.11.0 in c:\programdata\anaconda3\lib\site-packages (from tensorrec) (1.11.0)
Requirement already satisfied: tensorflow>=1.7.0 in c:\programdata\anaconda3\lib\site-packages (from tensorrec) (1.10.0)
Requirement already satisfied: numpy==1.14.1 in c:\programdata\anaconda3\lib\site-packages (from tensorrec) (1.14.1)
Requirement already satisfied: grpcio>=1.8.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow>=1.7.0->tensorrec) (1.16.0)
Requirement already satisfied: gast>=0.2.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow>=1.7.0->tensorrec) (0.2.0)
Requirement already satisfied: absl-py>=0.1.6 in c:\programdata\anaconda3\lib\site-packages (from tensorflow>=1.7.0->tensorrec) (0.6.1)
Requirement already satisfied: protobuf>=3.6.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow>=1.7.0->tensorrec) (3.6.1)
Collecting setuptools<=39.1.0 (from tensorflow>=1.7.0->tensorrec)
  Using cached https://files.pythonhosted.org/packages/8c/10/79282747f9169f21c053c562a0baa21815a8c7879be97abd930dbcf862e8/setuptools-39.1.0-py2.py3-none-any.whl
Requirement already satisfied: termcolor>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow>=1.7.0->tensorrec) (1.1.0)
Requirement already satisfied: tensorboard<1.11.0,>=1.10.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow>=1.7.0->tensorrec) (1.10.0)
Requirement already satisfied: astor>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from tensorflow>=1.7.0->tensorrec) (0.7.1)
Requirement already satisfied: wheel>=0.26 in c:\programdata\anaconda3\lib\site-packages (from tensorflow>=1.7.0->tensorrec) (0.32.3)
Requirement already satisfied: markdown>=2.6.8 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<1.11.0,>=1.10.0->tensorflow>=1.7.0->tensorrec) (2.6.11)
Requirement already satisfied: werkzeug>=0.11.10 in c:\programdata\anaconda3\lib\site-packages (from tensorboard<1.11.0,>=1.10.0->tensorflow>=1.7.0->tensorrec) (0.14.1)
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy: started
  Running setup.py bdist_wheel for scipy: finished with status 'error'
  Complete output from command C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\abcxyz~1\\AppData\\Local\\Temp\\pip-install-v_dy294s\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\abcxyz~1\AppData\Local\Temp\pip-wheel-9u1jx68t --python-tag cp36:
  lapack_opt_info:
  lapack_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\ProgramData\\Anaconda3\\lib', 'C:\\', 'C:\\ProgramData\\Anaconda3\\libs']
    NOT AVAILABLE
  
  openblas_lapack_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries openblas not found in ['C:\\ProgramData\\Anaconda3\\lib', 'C:\\', 'C:\\ProgramData\\Anaconda3\\libs']
  Unexpected IOError in C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\compaq.py
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\abcxyz~1\AppData\Local\Temp\pip-install-v_dy294s\scipy\setup.py", line 416, in <module>
      setup_package()
    File "C:\Users\abcxyz~1\AppData\Local\Temp\pip-install-v_dy294s\scipy\setup.py", line 412, in setup_package
      setup(**metadata)
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "C:\Users\abcxyz~1\AppData\Local\Temp\pip-install-v_dy294s\scipy\setup.py", line 336, in configuration
      config.add_subpackage('scipy')
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1024, in add_subpackage
      caller_level = 2)
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 993, in get_subpackage
      caller_level = caller_level + 1)
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 930, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 9, in configuration
      config.add_subpackage('cluster')
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1024, in add_subpackage
      caller_level = 2)
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 993, in get_subpackage
      caller_level = caller_level + 1)
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 930, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\cluster\setup.py", line 17, in configuration
      blas_opt = get_info('lapack_opt')
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 432, in get_info
      return cl().get_info(notfound_action)
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 624, in get_info
      self.calc_info()
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 1534, in calc_info
      openblas_info = get_info('openblas_lapack')
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 432, in get_info
      return cl().get_info(notfound_action)
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 624, in get_info
      self.calc_info()
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 1814, in calc_info
      f = new_fcompiler(c_compiler=c)
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\__init__.py", line 868, in new_fcompiler
      load_all_fcompiler_classes()
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\__init__.py", line 769, in load_all_fcompiler_classes
      __import__ (module_name)
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\compaq.py", line 57, in <module>
      class CompaqVisualFCompiler(FCompiler):
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\compaq.py", line 95, in CompaqVisualFCompiler
      raise e
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\compaq.py", line 81, in CompaqVisualFCompiler
      m.initialize()
    File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\msvccompiler.py", line 50, in initialize
      _MSVCCompiler.initialize(self)
    File "C:\ProgramData\Anaconda3\lib\distutils\msvc9compiler.py", line 374, in initialize
      vc_env = query_vcvarsall(VERSION, plat_spec)
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 147, in msvc9_query_vcvarsall
      return EnvironmentInfo(arch, ver).return_env()
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 1228, in return_env
      self.OSIncludes,
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 963, in OSIncludes
      sdkver = self._sdk_subdir
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 1057, in _sdk_subdir
      ucrtver = self.si.WindowsSdkLastVersion
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 604, in WindowsSdkLastVersion
      self.WindowsSdkDir, 'lib'))
    File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 809, in _use_last_dir_name
      for dir_name in reversed(os.listdir(path))
  FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'
  
  ----------------------------------------
  Running setup.py clean for scipy
  Complete output from command C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\abcxyz~1\\AppData\\Local\\Temp\\pip-install-v_dy294s\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  
  ----------------------------------------
Failed to build scipy
Installing collected packages: scipy, tensorrec, setuptools
  Found existing installation: scipy 1.1.0
    Uninstalling scipy-1.1.0:
      Successfully uninstalled scipy-1.1.0
  Running setup.py install for scipy: started
    Running setup.py install for scipy: finished with status 'error'
    Complete output from command C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\abcxyz~1\\AppData\\Local\\Temp\\pip-install-v_dy294s\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\abcxyz~1\AppData\Local\Temp\pip-record-0d7_zd25\install-record.txt --single-version-externally-managed --compile:
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    lapack_opt_info:
    lapack_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['C:\\ProgramData\\Anaconda3\\lib', 'C:\\', 'C:\\ProgramData\\Anaconda3\\libs']
      NOT AVAILABLE
    
    openblas_lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas not found in ['C:\\ProgramData\\Anaconda3\\lib', 'C:\\', 'C:\\ProgramData\\Anaconda3\\libs']
    Unexpected IOError in C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\compaq.py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\abcxyz~1\AppData\Local\Temp\pip-install-v_dy294s\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\abcxyz~1\AppData\Local\Temp\pip-install-v_dy294s\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\abcxyz~1\AppData\Local\Temp\pip-install-v_dy294s\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1024, in add_subpackage
        caller_level = 2)
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 993, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 930, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 9, in configuration
        config.add_subpackage('cluster')
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1024, in add_subpackage
        caller_level = 2)
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 993, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\misc_util.py", line 930, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\cluster\setup.py", line 17, in configuration
        blas_opt = get_info('lapack_opt')
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 432, in get_info
        return cl().get_info(notfound_action)
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 624, in get_info
        self.calc_info()
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 1534, in calc_info
        openblas_info = get_info('openblas_lapack')
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 432, in get_info
        return cl().get_info(notfound_action)
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 624, in get_info
        self.calc_info()
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 1814, in calc_info
        f = new_fcompiler(c_compiler=c)
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\__init__.py", line 868, in new_fcompiler
        load_all_fcompiler_classes()
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\__init__.py", line 769, in load_all_fcompiler_classes
        __import__ (module_name)
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\compaq.py", line 57, in <module>
        class CompaqVisualFCompiler(FCompiler):
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\compaq.py", line 95, in CompaqVisualFCompiler
        raise e
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\fcompiler\compaq.py", line 81, in CompaqVisualFCompiler
        m.initialize()
      File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\distutils\msvccompiler.py", line 50, in initialize
        _MSVCCompiler.initialize(self)
      File "C:\ProgramData\Anaconda3\lib\distutils\msvc9compiler.py", line 374, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 147, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 1228, in return_env
        self.OSIncludes,
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 963, in OSIncludes
        sdkver = self._sdk_subdir
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 1057, in _sdk_subdir
        ucrtver = self.si.WindowsSdkLastVersion
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 604, in WindowsSdkLastVersion
        self.WindowsSdkDir, 'lib'))
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 809, in _use_last_dir_name
        for dir_name in reversed(os.listdir(path))
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'
    
    ----------------------------------------
  Rolling back uninstall of scipy
  Failed building wheel for scipy
  Failed cleaning build dir for scipy
awsebcli 3.14.2 requires botocore>=1.0.1, which is not installed.
awsebcli 3.14.2 has requirement colorama<0.4.0,>=0.3.9, but you'll have colorama 0.4.0 which is incompatible.
awsebcli 3.14.2 has requirement PyYAML<=3.12,>=3.10, but you'll have pyyaml 3.13 which is incompatible.
Command "C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\abcxyz~1\\AppData\\Local\\Temp\\pip-install-v_dy294s\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\abcxyz~1\AppData\Local\Temp\pip-record-0d7_zd25\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\abcxyz~1\AppData\Local\Temp\pip-install-v_dy294s\scipy\

**Comment by jfkirk** [comment]
It looks like the issue is with the Scipy installation. Can you please try running `pip install scipy==0.19.1` and tell me if you see a similar error?

This will likely be solved by updating the Scipy dependency: https://github.com/jfkirk/tensorrec/issues/117
