### ISSUE TITLE
load_model() raising ValueError

### ISSUE THREAD

**Issue by jfkirk** [jfkirk/tensorrec#57]
Via e-mail from Lukas Brandt Brune:

```
Now I've been encountered another problem which I hope you could help me with. The problem lies within loading a saved model on another execution. From what I've gathered, tf.train.Saver() needs to be run inside a session and it looks to me that it's not (?). Upon calling load_model from another script I get ValueError: No variables to save.
I've tried calling it as:
TensorRec.load_model(dir_path)
and
model = TensorRec()
model.load_model(dir_path)
Either way, it's the the row 'saver = tf.train.Saver()' which fails every time. 
Would be really thankful if you could give me any pointer in how to proceed from here.

Btw, load_model is kinda the first that's happening in my script, maybe I'm mising to initialize something before?
```

**Comment by jfkirk** [comment]
Reproduced by adding `reset_default_graph` to the saver test
```
======================================================================
ERROR: test_save_and_load_model (test.test_tensorrec.TensorRecSavingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jkirk/dev/tensorrec/test/test_tensorrec.py", line 248, in test_save_and_load_model
    new_model = TensorRec.load_model(directory_path=self.test_dir)
  File "/Users/jkirk/dev/tensorrec/tensorrec/tensorrec.py", line 798, in load_model
    saver = tf.train.Saver()
  File "/Users/jkirk/dev/envs/tensorrec/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1239, in __init__
    self.build()
  File "/Users/jkirk/dev/envs/tensorrec/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1248, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/jkirk/dev/envs/tensorrec/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1272, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
```
