### ISSUE TITLE
How to setup proper environment

### ISSUE THREAD

**Issue by trenddev** [jfkirk/tensorrec#62]
@jfkirk This is a very interesting project. I try to setup my local environment and run some basic example code. I have following installed:
```
Python 3.5.5 :: Anaconda, Inc.
Tensorflow 1.4.1
CUDA 8.0
cudnn 6.0
```

However, I got following error:

```
Traceback (most recent call last):
  File "tensorrec_example.py", line 15, in <module>
    model.fit(interactions, user_features, item_features, epochs=5, verbose=True)
  File "/home/trend/.conda/envs/py_3.5/lib/python3.5/site-packages/tensorrec/tensorrec.py", line 533, in fit
    n_sampled_items=n_sampled_items)
  File "/home/trend/.conda/envs/py_3.5/lib/python3.5/site-packages/tensorrec/tensorrec.py", line 601, in fit_partial
    self._build_tf_graph(n_user_features=n_user_features, n_item_features=n_item_features)
  File "/home/trend/.conda/envs/py_3.5/lib/python3.5/site-packages/tensorrec/tensorrec.py", line 488, in _build_tf_graph
    self._record_graph_hook_names()
  File "/home/trend/.conda/envs/py_3.5/lib/python3.5/site-packages/tensorrec/tensorrec.py", line 171, in _record_graph_hook_names
    output_classes = hook._output_classes
AttributeError: 'Iterator' object has no attribute '_output_classes'
```

Any ideas? Thank you!

**Comment by jfkirk** [comment]
Hey @trenddev ! Thanks for checking it out.

I think your problem is a TensorFlow version mismatch. TensorRec currently runs on TensorFlow 1.7.

You can update all of your requirements by downloading requirements.txt and running:

```
pip install -r requirements.txt
```

Closing for now -- if you run in to more problems, feel free to re-open this issue.
