### ISSUE TITLE
getting error while running test_movielens.py

### ISSUE THREAD

**Issue by sujit420** [jfkirk/tensorrec#65]
I am not able to execute test_movielens.py as I am getting below error:
Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/sujitmishra/tensorrec/test/test_movielens.py", line 26, in test_movie_lens_fit
    epochs=5)
  File "/Users/sujitmishra/tensorrec/tensorrec/tensorrec.py", line 533, in fit
    n_sampled_items=n_sampled_items)
  File "/Users/sujitmishra/tensorrec/tensorrec/tensorrec.py", line 601, in fit_partial
    self._build_tf_graph(n_user_features=n_user_features, n_item_features=n_item_features)
  File "/Users/sujitmishra/tensorrec/tensorrec/tensorrec.py", line 488, in _build_tf_graph
    self._record_graph_hook_names()
  File "/Users/sujitmishra/tensorrec/tensorrec/tensorrec.py", line 171, in _record_graph_hook_names
    output_classes = hook._output_classes
AttributeError: 'Iterator' object has no attribute '_output_classes'

Help me in fixing this.

**Comment by jfkirk** [comment]
Hi @sujit420 -- This error comes from a TensorFlow version mismatch. TensorRec is built on TensorFlow 1.7.0 (right now). Try updating your TensorFlow version, and this error should go away.

I'm closing this issue for now. If this doesn't fix your problem, please re-open it.
